version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: <%= ENV['DB_PASSWORD'] %>
      POSTGRES_USER: <%= ENV['DB_USERNAME'] %>
      POSTGRES_DB: your_project_development
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
