version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: myuser
      POSTGRES_DB: your_project_development
  web:
    build: .
    command: bundle exec rails s -p 3001 -b '0.0.0.0' # ポート3001に変更
    volumes:
      - .:/app
    ports:
      - "3001:3001" # ここも3001に変更
    depends_on:
      - db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
