# fly.toml app configuration file generated for seisyun-songs on 2023-08-11T13:49:30+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seisyun-songs"
primary_region = "nrt"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
